hiu:
  id: 10000005
  name: Max Health Care
  callbackurl:  http://localhost:8003/data/notification
  consentmanager:
    url: http://localhost:9000/
  dataflowservice:
    defaultPageSize: 20
    maxPageSize: 100
    localStoragePath: /tmp/
  centralregistry:
    url: http://localhost:8082/
  database:
    host: localhost
    port: 5432
    schema: health_information_user
    user: postgres
    password: postgres
    poolSize: 5
spring:
  rabbitmq:
    host: localhost
    port: 5672
  codec:
    max-in-memory-size: 500MB
