hiu:
  id: 10000005
  name: Max Health Care
  consentmanager:
    url: http://locahost:8081/
  dataflowservice:
    defaultPageSize: 20
    maxPageSize: 100
    localStoragePath: /tmp/hiu/data/
  centralregistry:
    url: http://localhost:8082/
  database:
    host: localhost
    port: 5432
    schema: health_information_user
    user: postgres
    password: postgres
    poolSize: 5
spring:
  rabbitmq:
    host: localhost
    port: 5672
