hiu:
  id: 10000005
  name: Max Health Care
  callbackurl: http://localhost:8003
  consentmanager:
    url: http://localhost:9000
  dataflowservice:
    defaultPageSize: 20
    maxPageSize: 100
    localStoragePath: /tmp/
  centralregistry:
    url: http://localhost:9001/auth
    clientId: 10000005
    clientSecret: 435cbced-9d57-4e35-9de8-0c2315d841df
  database:
    host: localhost
    port: 5432
    schema: health_information_user
    user: postgres
    password: postgres
    poolSize: 5
  dataflow:
    offsetInDays: 2
  dicomserver:
    url: http://localhost:8042/
    user: orthanc
    password: orthanc
spring:
  rabbitmq:
    host: localhost
    port: 5672
  codec:
    max-in-memory-size: 500MB
