hiu:
  id: 10000005
  name: Max Health Care
  callbackurl: http://localhost:8003
  consentmanager:
    url: http://localhost:9000
  dataflowservice:
    defaultPageSize: 20
    maxPageSize: 100
    localStoragePath: /tmp/
  centralregistry:
    url: http://host.docker.internal:8080
    clientId: 10000005
    clientSecret: b435af20-5006-4932-bca7-74aabdf8a78d
  database:
    host: localhost
    port: 5432
    schema: health_information_user
    user: postgres
    password: postgres
    poolSize: 5
  dataflow:
    offsetInDays: 2
  dicomserver:
    url: http://localhost:8042
    user: orthanc
    password: orthanc
spring:
  rabbitmq:
    host: localhost
    port: 5672
  codec:
    max-in-memory-size: 500MB
