server:
  port: 8003
hiu:
  id: 10000005
  name: Max Health Care
  dataPushUrl: http://localhost:8003/data/notification
  consentNotificationUrl: http://localhost:8003/consent/notification
  valueSets: classpath:/static/ValueSet/ncg-valuesets.json
  hfrAffinityDomains: ${HFR_AFFINITY_DOMAINS:hfr.projecteka.in}
  consentmanager:
    suffix: ncg
    url: http://localhost:9000
  dataflowservice:
    defaultPageSize: 20
    maxPageSize: 100
    localStoragePath: /tmp/
  centralregistry:
    url: http://localhost:8080
  database:
    host: localhost
    port: 5432
    schema: health_information_user
    user: postgres
    password: postgres
    poolSize: 5
  dataflow:
    offsetInDays: 2
    usingGateway: true
  dicomserver:
    url: http://localhost:8042
    user: orthanc
    password: orthanc
  gatewayservice:
    baseUrl: http://localhost:8080/v0.5
    requestTimeout: 2000
    clientId: 10000005
    clientSecret: 95ca9a9d-1473-4172-9d87-0fd4d87ee1d6
    jwkUrl: http://localhost:8080/v0.5/certs
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  codec:
    max-in-memory-size: 500MB
