openapi: 3.0.0
info:
  version: 0.0.1
  title: Health Information User
  description: >
    "Health information User" refers to an entity that wishes to consume the
    services of the Health Data Consent Manager and obtain aggregated health
    information for providing services to the patient .

servers:
  - url: http://localhost:8000
    description: Dev

tags:
  - name: discover
  - name: consent

paths:
  # consent-manager service
  /consent-requests:
    post:
      tags:
        - consent
      summary: Create consent request
      description: Creates a consent request to get data about a patient by HIU user.
      operationId: createConsentRequest
      parameters:
        - $ref: '#/components/parameters/authorization'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConsentRequest'
      responses:
        '200':
          description: Request created in the consent manager
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid

  # discover service
  /patients/{patient-id}:
    get:
      tags:
        - discover
      summary: Search patient
      description: Search patients in the respective health information consent manager.
      parameters:
        - $ref: '#/components/parameters/authorization'
        - name: patient-id
          in: path
          required: true
          schema:
            type: string
            format: <user-id>@<ncg-id>
            example: batman@ncg
      responses:
        '200':
          description: Successful creation of consent artefact.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PatientSearchRepresentation'
components:
  parameters:
    authorization:
      name: Authorization
      in: header
      required: true
      description: Bearer token which was issued after successful login.
      schema:
        type: string

  schemas:
    PatientSearchRepresentation:
      type: object
      properties:
        patient:
          $ref: '#/components/schemas/PatientRepresentation'

    ConsentManagerPatientID:
      type: object
      properties:
        id:
          type: string
          format: <user-id>@<ncg-id>
          example: batman@ncg

    PatientRepresentation:
      allOf:
        - $ref: '#/components/schemas/ConsentManagerPatientID'
        - type: object
          properties:
            display:
              type: string

    HITypeEnum:
      type: string
      enum:
        - HIType1
        - HIType2
        - HIType3
        - HIType4
        - HIType5
      example: "DiagnosticReport"

    ConsentRequest:
      type: object
      properties:
        consent:
          type: object
          properties:
            patient:
              allOf:
                - $ref: '#/components/schemas/ConsentManagerPatientID'
            purpose:
              type: object
              properties:
                code:
                  type: string
                  example: "ReferralService"
            hitypes:
              type: array
              items:
                $ref: '#/components/schemas/HITypeEnum'
            permission:
              type: object
              properties:
                dateRange:
                  type: object
                  properties:
                    from:
                      type: string
                      format: datetime
                    to:
                      type: string
                      format: datetime
                dataExpiryAt:
                  type: string
                  format: date-time