apiVersion: v1
kind: Service
metadata:
  name: {{ include "hiu.fullname" . }}
  labels:
    {{- include "hiu.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8003
      protocol: TCP
      name: http
  selector:
    {{- include "hiu.selectorLabels" . | nindent 4 }}
