apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-hiu
  namespace: nha-app
  labels:
    app: patient-hiu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-hiu
  template:
    metadata:
      labels:
        app: patient-hiu
    spec:
      containers:
        - name: patient-hiu
          image: ganesan92/health-information-user:de5346f
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "500m"
              memory: "1024Mi"
            limits:
              cpu: "500m"
              memory: "1024Mi"
          livenessProbe:
            httpGet:
              path: /v0.5/heartbeat
              port: 8003
            initialDelaySeconds: 120
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /v0.5/readiness
              port: 8003
            initialDelaySeconds: 120
            timeoutSeconds: 10
          env:
            - name: CENTRAL_REGISTRY_JWK_URL
              value: http://client-registry:8080/certs
            - name: CENTRAL_REGISTRY_URL
              value: http://client-registry:8080
            - name: CONSENT_MANAGEMENT_SUFFIX
              value: '@pmjay'
            - name: CONSENT_MANAGEMENT_URL
              value: http://consent-manager:8000
            - name: CONSENT_MANAGER_DB_NAME
              value: health_information_user
            - name: CONSENT_NOTIFICATION_URL
              value: http://hiu:8003/consent/notification
            - name: DATA_PUSH_URL
              value: http://hiu:8003/data/notification
            - name: DB_CONNECTION_POOL_SIZE
              value: "5"
            - name: DEFAULT_PAGE_SIZE
              value: "20"
            - name: GATEWAY_BASE_URL
              value: http://gateway:8000/v0.5
            - name: GATEWAY_REQUEST_TIMEOUT
              value: "8000"
            - name: HIU_CLIENT_ID
              value: "10000002"
            - name: HIU_CLIENT_SECRET
              valueFrom:
                  secretKeyRef:
                    name: hiu-secrets
                    key: HIU_CLIENT_SECRET
            - name: HIU_ID
              value: "10000002"
            - name: HIU_NAME
              value: Max Health Care
            - name: LOCAL_STORAGE_PATH
              value: /tmp/
            - name: MAX_IN_MEMORY_SIZE
              value: 500MB
            - name: MAX_PAGE_SIZE
              value: "100"
            - name: OFFSET_IN_DAYS
              value: "2"
            - name: ORTHANC_PASSWORD
              valueFrom:
                  secretKeyRef:
                    name: hiu-secrets
                    key: ORTHANC_PASSWORD
            - name: ORTHANC_SERVER_URL
              value: http://orthanc:8042
            - name: ORTHANC_USERNAME
              value: orthanc
            - name: POSTGRES_HOST
              value: nhadcl-postges-1.nhadclmgm.tatacommunications.com
            - name: POSTGRES_PASSWORD
              valueFrom:
                  secretKeyRef:
                    name: hiu-secrets
                    key: POSTGRES_PASSWORD
            - name: POSTGRES_PORT
              value: "5633"
            - name: POSTGRES_USER
              value: postgres
            - name: USING_GATEWAY
              value: "true"
            - name: GATEWAY_JWK_URL
              value: http://gateway:8000/v0.5/certs
            - name: RABBITMQ_HOST
              value: rabbitmq.nhadclmgm.tatacommunications.com
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME 
              value: admin
            - name: RABBITMQ_PASSWORD
              value: "TA7a3@!"
            - name: IDENTITY_JWK_URL
              value: http://keycloak:8080/auth/realms/consent-manager/protocol/openid-connect/certs
            - name: USING_GATEWAY
              value: 'true'
          ports:
            - name: http
              containerPort: 8003
              protocol: TCP
          volumeMounts:
            - name: patient-hiu-data
              mountPath: /mnt/patient-hiu-data
      volumes:
        - name: patient-hiu-data
          persistentVolumeClaim:
              claimName: patient-hiu-data
