apiVersion: v2
name: patient-hiu
description: A Helm chart for patient-hiu

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

